backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "cursos"
    label: "Cursos"
    folder: "src/pages/cursos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "course-page"}
      - {label: "Nome do Curso", name: "title", widget: "string"}
      - {label: "Descrição para Thumbnail", name: "thumbnailDescription", widget: "text"}
      - {label: "Imagem Thumbnail", name: "thumbnailImage", widget: image}
      - {label: "Image Landing Curso", name: "bgImage", widget: image}
      - {label: "Título Landing Curso", name: "titleLanding", widget: "string"}
      - {label: "Curriculo Curso", name: "curriculum", widget: "markdown"}
      - {label: "Conteúdo", name: "description", widget: "markdown"}
      - {label: "Lista", name: "details", widget: "list", fields: [
        {label: Icone, name: icon, widget: image},
        {label: Texto, name: text, widget: string}
      ]}
      - {label: "Módulos", name: "modules", widget: "list", fields: [
          {label: "Título", name: title, widget: string},
          {label: "Descrição", name: description, widget: markdown}
      ]}

  - name: "especialistas"
    label: "Especialistas"
    folder: "src/pages/especialistas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specialist-page"}
      - {label: "Nome do Especialista", name: "title", widget: "string"}
      - {label: "Descrição para Thumbnail", name: "thumbnailDescription", widget: "text"}
      - {label: "Imagem Thumbnail", name: "thumbnailImage", widget: image }
      - {label: "Image Landing Especialista", name: "bgImage", widget: image}
      - {label: "Título Landing Especialista", name: "titleLanding", widget: "string"}
      - {label: "Curriculo Especialista", name: "curriculum", widget: "markdown"}
      - {label: "Conteúdo", name: "description", widget: "markdown"}
      - {label: "Lista", name: "details", widget: "list", fields: [
          {label: Icone, name: icon, widget: image},
          {label: Texto, name: text, widget: string}
        ]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: HeroSection, name: hero, widget: object, fields: [
              {label: "Texto principal", name: heading, widget: string},
              {label: "Texto Pequeno Acima do Botão", name: callActionSmall, widget: text, required: false},
              {label: "Texto Grande Acima do Botão", name: callActionBig, widget: text, required: false},
              {label: "Text Botão CTA", name: buttonText, widget: text},
              {label: "Imagem fundo Desktop", name: imageDesktop, widget: image},
              {label: "Imagem fundo Mobile", name: imageMobile, widget: image}
            ]}
          - {label: "Seção conteúdo", name: contentHeaders, widget: object, fields: [
              {label: "Título Cabeçalho", name: title, widget: string},
              {label: "Título da seção", name: heading, widget: string},
              {label: "Subtítulo", name: subHeading, widget: string},
              {label: "Texto especialistas", name: headingSpecialist, widget: string},
              {label: "Texto cursos", name: headingCourses, widget: string},
            ]}
          - {label: "Como Funciona", name: howItWorks, widget: object, fields: [
             {label: "Título Cabeçalho", name: title, widget: string},
             {label: "Título da sessão", name: heading, widget: string},
             {label: "Caixas como funciona", name: boxes, widget: object, fields: [
              {label: "Texto topo centro", name: refresh, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
              {label: "Texto topo esquerdo", name: organizacao, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
              {label: "Texto topo direito", name: atualizacao, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
              {label: "Texto abaixo centro", name: especialistas, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
              {label: "Texto abaixo esquerda", name: qualidade, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
              {label: "Texto abaixo direita", name: diversidade, widget: object, fields: [
                {label: "Título", name: title, widget: string},
                {label: "Descrição", name: description, widget: text},
              ]},
             ]},
          ]}
          - {label: "Banner CTA", name: banner, widget: object, fields: [
              {label: "Texto principal", name: title, widget: string},
              {label: "Texto botão", name: buttonText, widget: string},
            ]}
          - {label: "Banner CTA Especialista", name: bannerSpecialist, widget: object, fields: [
            {label: "Texto principal", name: title, widget: string},
            {label: "Texto Secundário", name: secondaryTitle, widget: string, required: false},
            {label: "Texto botão", name: buttonText, widget: string},
            ]}
          - {label: "Banner CTA Curso", name: bannerCourse, widget: object, fields: [
            {label: "Texto principal", name: title, widget: string},
            {label: "Texto Secundário", name: secondaryTitle, widget: string, required: false},
            {label: "Texto botão", name: buttonText, widget: string},
            ]}
          - {label: "Seja membro", name: member, widget: object, fields: [
              {label: "Título cabeçalho", name: title, widget: string},
              {label: "Texto principal", name: description, widget: markdown},
              {label: "Título CTA", name: titleCTA, widget: string},
              {label: "Texto botão CTA", name: buttonText, widget: string},
              {label: "Imagem de fundo", name: bgImage, widget: image}
            ]}
          - {label: "Seção depoimentos", name: testimonials, widget: object, fields: [
              {label: "Título cabeçalho", name: title, widget: string},
              {label: "Subtítulo", name: description, widget: string},
              {label: "Texto botão CTA", name: buttonText, widget: string},
              {label: Depoimentos, name: testimonialList, widget: list, fields: [
                {label: Foto, name: photo, widget: image, required: false},
                {label: Nome, name: name, widget: string},
                {label: Subtitulo, name: subtitle, widget: string},
                {label: Texto, name: text, widget: markdown}
              ]}
            ]}

      - file: "src/pages/registro/index.md"
        label: "Formulário"
        name: "register"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "register-page"}
          - {label: "Primeiro Passo", name: firstStep, widget: object, fields: [
            {label: "Título", name: title, widget: string},
            {label: "Texto botão", name: buttonText, widget: string}
            ]}
          - {label: "Segundo Passo", name: secondStep, widget: object, fields: [
            {label: "Título", name: title, widget: string},
            {label: "Link vídeo Youtube", name: linkYT, widget: string},
            {label: "Texto botão", name: buttonText, widget: string}
          ]}
          - {label: "Terceiro Passo", name: thirdStep, widget: object, fields: [
            {label: "Título", name: title, widget: string},
            {label: "Texto", name: text, widget: string},
            {label: "Texto botão", name: buttonText, widget: string},
            {label: "Texto botão secundário", name: buttonTextSecondary, widget: string, required: false}
            ]}

  - name: "landings"
    label: "Landing Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
        - {label: "Url da página", name: "title", widget: "string"}
        - {label: "Título da aba na página", name: "titlePage", widget: "string"}
        - {label: "Descrição da página", name: "descriptionPage", widget: "string"}
        - {label: "Imagem de fundo das páginas", name: "bgImage", widget: "image", required: false}
        - {label: "Texto acima do vídeo na página 01", name: "textAbovePg1", widget: "markdown", required: false}
        - {label: "Código do vídeo Youtube página 01", name: "youtubePg01", widget: "string", required: false}
        - {label: "Texto abaixo do vídeo na página 01", name: "textBelowPg01", widget: "markdown", required: false}
        - {label: "Texto Botão página 01", name: "buttonPg01", widget: "string"}
        - {label: "Texto acima do vídeo na página 02", name: "textAbovePg2", widget: "markdown", required: false}
        - {label: "Código do vídeo Youtube página 02", name: "youtubePg02", widget: "string", required: false}
        - {label: "Texto abaixo do vídeo na página 02", name: "textBelowPg02", widget: "markdown", required: false}
        - {label: "Texto Botão página 02", name: "buttonPg02", widget: "string"}
        - {label: "Link Botão página 02", name: "buttonLink", widget: "string"}
        - {label: "Texto Botão secondário página 02", name: "buttonSecondaryPg02", widget: "string", required: false}
        - {label: "Link Botão secondário página 02", name: "buttonSecondaryLink", widget: "string", required: false}
        - {label: "Cor de fundo na página (HEX Code)", name: "bgColor", widget: "string", required: false}
        - {label: "Cor da letra na página (HEX Code)", name: "letterColor", widget: "string", required: false}
